# Generated by Django 5.0.1 on 2024-02-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nombre_commentaire',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nombre_like',
        ),
    ]
